// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: TestStandTelem

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_LiveDataScreen
void ui_LiveDataScreen_screen_init(void);
lv_obj_t *ui_LiveDataScreen;
lv_obj_t *ui_ThrustChart1;
lv_obj_t *ui_ChartYLabel;
lv_obj_t *ui_ResultsPanel;
lv_obj_t *ui_MaxThrustLabel;
lv_obj_t *ui_MaxThrustValue;
lv_obj_t *ui_ImpulseLabel;
lv_obj_t *ui_ImpulseValue;
lv_obj_t *ui_AvgThrustLabel;
lv_obj_t *ui_AvgThrustValue;


// SCREEN: ui_ResultsScreen
void ui_ResultsScreen_screen_init(void);
lv_obj_t *ui_ResultsScreen;
lv_obj_t *ui_FinalResultsPanel;
lv_obj_t *ui_MaxThrustLabelFinal;
lv_obj_t *ui_MaxThrustValueFinal;
lv_obj_t *ui_AvgThrustLabelFinal;
lv_obj_t *ui_AvgThrustValueFinal;
lv_obj_t *ui_ImpulseLabelFinal;
lv_obj_t *ui_ImpulseValueFinal;
lv_obj_t *ui_MotorClassificationValue;
lv_obj_t *ui_BurnDurationLabel;
lv_obj_t *ui_BurnDurationValue;
lv_obj_t *ui_ThrustChartFinal;


// SCREEN: ui_DisconnectScreen
void ui_DisconnectScreen_screen_init(void);
lv_obj_t *ui_DisconnectScreen;
lv_obj_t *ui_DisconnectPanel;
lv_obj_t *ui_DisconnectLabel;
void ui_event____initial_actions0( lv_event_t * e);
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event____initial_actions0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      CheckConnctionStatus( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_LiveDataScreen_screen_init();
ui_ResultsScreen_screen_init();
ui_DisconnectScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

lv_disp_load_scr(ui____initial_actions0);
lv_disp_load_scr( ui_LiveDataScreen);
}
