// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: TestStandTelem

#ifndef _TESTSTANDTELEM_UI_H
#define _TESTSTANDTELEM_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_LiveDataScreen
void ui_LiveDataScreen_screen_init(void);
extern lv_obj_t *ui_LiveDataScreen;
extern lv_obj_t *ui_ThrustChart1;
extern lv_obj_t *ui_ChartYLabel;
extern lv_obj_t *ui_ResultsPanel;
extern lv_obj_t *ui_MaxThrustLabel;
extern lv_obj_t *ui_MaxThrustValue;
extern lv_obj_t *ui_ImpulseLabel;
extern lv_obj_t *ui_ImpulseValue;
extern lv_obj_t *ui_AvgThrustLabel;
extern lv_obj_t *ui_AvgThrustValue;
// SCREEN: ui_ResultsScreen
void ui_ResultsScreen_screen_init(void);
extern lv_obj_t *ui_ResultsScreen;
extern lv_obj_t *ui_FinalResultsPanel;
extern lv_obj_t *ui_MaxThrustLabelFinal;
extern lv_obj_t *ui_MaxThrustValueFinal;
extern lv_obj_t *ui_AvgThrustLabelFinal;
extern lv_obj_t *ui_AvgThrustValueFinal;
extern lv_obj_t *ui_ImpulseLabelFinal;
extern lv_obj_t *ui_ImpulseValueFinal;
extern lv_obj_t *ui_MotorClassificationValue;
extern lv_obj_t *ui_BurnDurationLabel;
extern lv_obj_t *ui_BurnDurationValue;
extern lv_obj_t *ui_ThrustChartFinal;
// SCREEN: ui_DisconnectScreen
void ui_DisconnectScreen_screen_init(void);
extern lv_obj_t *ui_DisconnectScreen;
extern lv_obj_t *ui_DisconnectPanel;
extern lv_obj_t *ui_DisconnectLabel;
void ui_event____initial_actions0( lv_event_t * e);
extern lv_obj_t *ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
