// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: TestStandTelem

#include "ui.h"

void ui_DisconnectScreen_screen_init(void)
{
ui_DisconnectScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_DisconnectScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DisconnectPanel = lv_obj_create(ui_DisconnectScreen);
lv_obj_set_width( ui_DisconnectPanel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DisconnectPanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_DisconnectPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_DisconnectPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DisconnectPanel, lv_color_hex(0xB90000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DisconnectPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_DisconnectPanel, lv_color_hex(0x9E0505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_DisconnectPanel, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_DisconnectPanel, true, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DisconnectLabel = lv_label_create(ui_DisconnectPanel);
lv_obj_set_width( ui_DisconnectLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DisconnectLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_DisconnectLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DisconnectLabel,"No Connection To Test Stand\n");
lv_obj_set_style_text_color(ui_DisconnectLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DisconnectLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}
