// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: TestStandTelem

#include "ui.h"

void ui_ResultsScreen_screen_init(void)
{
ui_ResultsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ResultsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FinalResultsPanel = lv_obj_create(ui_ResultsScreen);
lv_obj_set_width( ui_FinalResultsPanel, 310);
lv_obj_set_height( ui_FinalResultsPanel, 35);
lv_obj_set_x( ui_FinalResultsPanel, 5 );
lv_obj_set_y( ui_FinalResultsPanel, 0 );
lv_obj_clear_flag( ui_FinalResultsPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_FinalResultsPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FinalResultsPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_FinalResultsPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_FinalResultsPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MaxThrustLabelFinal = lv_label_create(ui_FinalResultsPanel);
lv_obj_set_width( ui_MaxThrustLabelFinal, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MaxThrustLabelFinal, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MaxThrustLabelFinal, -15 );
lv_obj_set_y( ui_MaxThrustLabelFinal, -15 );
lv_label_set_text(ui_MaxThrustLabelFinal,"Maximum:");
lv_obj_set_style_text_font(ui_MaxThrustLabelFinal, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MaxThrustValueFinal = lv_label_create(ui_MaxThrustLabelFinal);
lv_obj_set_width( ui_MaxThrustValueFinal, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MaxThrustValueFinal, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MaxThrustValueFinal, 70 );
lv_obj_set_y( ui_MaxThrustValueFinal, 0 );
lv_label_set_long_mode(ui_MaxThrustValueFinal,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_MaxThrustValueFinal,"--");
lv_obj_set_style_text_font(ui_MaxThrustValueFinal, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AvgThrustLabelFinal = lv_label_create(ui_FinalResultsPanel);
lv_obj_set_width( ui_AvgThrustLabelFinal, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AvgThrustLabelFinal, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AvgThrustLabelFinal, -15 );
lv_obj_set_y( ui_AvgThrustLabelFinal, 0 );
lv_label_set_text(ui_AvgThrustLabelFinal,"Average: ");
lv_obj_set_style_text_font(ui_AvgThrustLabelFinal, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AvgThrustValueFinal = lv_label_create(ui_AvgThrustLabelFinal);
lv_obj_set_width( ui_AvgThrustValueFinal, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AvgThrustValueFinal, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AvgThrustValueFinal, 70 );
lv_obj_set_y( ui_AvgThrustValueFinal, 0 );
lv_label_set_long_mode(ui_AvgThrustValueFinal,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_AvgThrustValueFinal,"--");
lv_obj_set_style_text_font(ui_AvgThrustValueFinal, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImpulseLabelFinal = lv_label_create(ui_FinalResultsPanel);
lv_obj_set_width( ui_ImpulseLabelFinal, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImpulseLabelFinal, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImpulseLabelFinal, 100 );
lv_obj_set_y( ui_ImpulseLabelFinal, 0 );
lv_label_set_text(ui_ImpulseLabelFinal,"Impulse: ");
lv_obj_set_style_text_font(ui_ImpulseLabelFinal, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImpulseValueFinal = lv_label_create(ui_ImpulseLabelFinal);
lv_obj_set_width( ui_ImpulseValueFinal, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImpulseValueFinal, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImpulseValueFinal, 70 );
lv_obj_set_y( ui_ImpulseValueFinal, 0 );
lv_label_set_long_mode(ui_ImpulseValueFinal,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_ImpulseValueFinal,"--");
lv_obj_set_style_text_font(ui_ImpulseValueFinal, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MotorClassificationValue = lv_label_create(ui_FinalResultsPanel);
lv_obj_set_width( ui_MotorClassificationValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MotorClassificationValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MotorClassificationValue, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_MotorClassificationValue,"H90");
lv_obj_set_style_text_font(ui_MotorClassificationValue, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BurnDurationLabel = lv_label_create(ui_FinalResultsPanel);
lv_obj_set_width( ui_BurnDurationLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BurnDurationLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BurnDurationLabel, 100 );
lv_obj_set_y( ui_BurnDurationLabel, -15 );
lv_label_set_text(ui_BurnDurationLabel,"Duration: ");
lv_obj_set_style_text_font(ui_BurnDurationLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BurnDurationValue = lv_label_create(ui_BurnDurationLabel);
lv_obj_set_width( ui_BurnDurationValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BurnDurationValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BurnDurationValue, 70 );
lv_obj_set_y( ui_BurnDurationValue, 0 );
lv_obj_set_align( ui_BurnDurationValue, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_BurnDurationValue,"--");

ui_ThrustChartFinal = lv_chart_create(ui_ResultsScreen);
lv_obj_set_width( ui_ThrustChartFinal, 300);
lv_obj_set_height( ui_ThrustChartFinal, 120);
lv_obj_set_x( ui_ThrustChartFinal, 10 );
lv_obj_set_y( ui_ThrustChartFinal, -10 );
lv_obj_set_align( ui_ThrustChartFinal, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_ThrustChartFinal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags
lv_chart_set_type( ui_ThrustChartFinal, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_ThrustChartFinal, 50);
lv_chart_set_range( ui_ThrustChartFinal, LV_CHART_AXIS_PRIMARY_Y, 0, 1200);
lv_chart_set_range( ui_ThrustChartFinal, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
lv_chart_set_div_line_count( ui_ThrustChartFinal, 10, 30);
lv_chart_set_axis_tick( ui_ThrustChartFinal, LV_CHART_AXIS_PRIMARY_X, 2, 3, 10, 1, false, 50);
lv_chart_set_axis_tick( ui_ThrustChartFinal, LV_CHART_AXIS_PRIMARY_Y, 5, 0, 5, 1, false, 50);
lv_chart_set_axis_tick( ui_ThrustChartFinal, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
lv_chart_series_t* ui_ThrustChartFinal_series_1 = lv_chart_add_series(ui_ThrustChartFinal, lv_color_hex(0xE60019), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_ThrustChartFinal_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0,0,10,20,40,80,800,40,20,10,0,0,10,20,40,80,800,40,20,10,0,0,10,20,40,80,800,40,20,10,0,0,10,20,40,80,800,40,20,10,0 };
lv_chart_set_ext_y_array(ui_ThrustChartFinal, ui_ThrustChartFinal_series_1, ui_ThrustChartFinal_series_1_array);
lv_obj_set_style_bg_color(ui_ThrustChartFinal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ThrustChartFinal, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_color(ui_ThrustChartFinal, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_ThrustChartFinal, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_width(ui_ThrustChartFinal, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_line_width(ui_ThrustChartFinal, 2, LV_PART_ITEMS| LV_STATE_DEFAULT);

lv_obj_set_style_outline_color(ui_ThrustChartFinal, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ThrustChartFinal, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_ThrustChartFinal, 1, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_ThrustChartFinal, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_size(ui_ThrustChartFinal, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);


}
